GROQ_API_KEY1 = "your_api_key1"
GROQ_API_KEY2 = "your_api_key2"
GROQ_API_KEY3 = "your_api_key3"
GROQ_API_KEY4 = "your_api_key4"
GROQ_API_KEY5 = "your_api_key5"
GROQ_API_KEY6 = "your_api_key6"
GROQ_API_KEY7 = "your_api_key7"
GROQ_API_KEY8 = "your_api_key8"
GROQ_API_KEY9 = "your_api_key9"
GROQ_API_KEY10 = "your_api_key10"

host = "your_db_hostname"
user = "your_db_username"
password = "your_db_password"

#rename the file to secrets.toml